name: Renew Certificates
on:
  workflow_dispatch:

jobs:
  renew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Nuke and recreate certs
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          TEAMID: ${{ secrets.TEAMID }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          bundle exec fastlane nuke_certs
          bundle exec fastlane certs
