name: Renew Certificates
on:
  workflow_dispatch:

jobs:
  renew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Nuke and recreate certs
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY_OWNER: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          echo "y" | bundle exec fastlane match nuke distribution
          bundle exec fastlane match appstore
