name: Renew Certificates
on:
  workflow_dispatch:

jobs:
  renew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Recreate certs
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          TEAMID: ${{ secrets.TEAMID }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          echo "$FASTLANE_KEY" > fastlane/api_key.p8
          bundle exec fastlane match appstore \
            --force \
            --skip_provisioning_profiles true \
            --api_key_path fastlane/api_key.p8 \
            --api_key_issuer_id "$FASTLANE_ISSUER_ID" \
            --api_key_key_id "$FASTLANE_KEY_ID" \
            --git_basic_authorization $(echo -n "$GITHUB_REPOSITORY_OWNER:$GH_PAT" | base64)
          rm -f fastlane/api_key.p8
